### PR TITLE
projects/01drv_ism330: Fix ISM330 crashing because the IMU is configured too soon after boot

### LINKED ISSUE #320: 01drv_ism330 hangs trying to configure the IMU
It turns out you have to wait a few miliseconds before before writing to the IMU, to give it time to powerup.
Found this out while working on #316

### PR DESCRIPTION
**Pull request by SaidAlvarado**
fixes #320

### CODE REVIEW

File: projects/01drv_ism330/01drv_ism330.c [hunk 1]
```diff
@@ -24,10 +24,12 @@ static ism330_gyro_data_t gyro_data;
 int main(void) {
 
     db_board_init();
-    db_ism330_init(&db_sda, &db_scl);
+    // Init the timer
     db_timer_hf_init(0);
+    db_timer_hf_delay_ms(0, 500);  // Wait for the IMU to power-up
```
Comment (aabadie) [inline projects/01drv_ism330/01drv_ism330.c:29]: Why not do this straight at the beginning the `db_ism330_init` function? (That would also mean the driver library has a dependency on "timer_hf"). Also why not use the low frequency timer instead of the high frequency one?

Comment (SaidAlvarado) [reply projects/01drv_ism330/01drv_ism330.c:29]: No reason, time_hf was already available in the example.
I'll add it inside the driver

**Review by aabadie — APPROVED** [review]
